# Render Blueprint API
# https://render.com/docs/blueprint-spec

services:
  - type: web
    name: relevance-ai-mcp
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host=0.0.0.0 --port=$PORT
    envVars:
      - key: PORT
        value: 10000
      - key: RELEVANCE_API_KEY
        sync: false  # Set this in the Render dashboard
      - key: RELEVANCE_API_BASE_URL
        value: "https://api.relevanceai.com/v1"
      - key: CORS_ORIGINS
        value: "*"
      - key: DEBUG
        value: "false"
      - key: LOG_LEVEL
        value: "info"
    healthCheckPath: /health
    healthCheckTimeout: 10
    autoDeploy: true
    domains:
      - relevance-ai-mcp.onrender.com  # Will be auto-assigned by Render
